### ISSUE TITLE
pgfmorepageslayouts.code.tex missing from CTAN upload

### ISSUE THREAD

**Issue by dcpurton** [loopspace/pgfmorepages#2]
I think you missed uploading `pgfmorepageslayouts.code.tex` to CTAN.

So this file does not appear in TeXLive. Consequently `\pgfmorepagesloadextralayouts` generates an error.

**Comment by loopspace** [comment]
Ooops!  Well spotted.  Thanks for letting me know.

**Comment by loopspace** [comment]
I've finally gotten round to uploading a new version to CTAN with the missing file included.
