### ISSUE TITLE
Incompatability with `changepage`

### ISSUE THREAD

**Issue by keyneston** [loopspace/pgfmorepages#7]
# Reproduction

1. Create file `test.tex` with the following contents:

```latex
\documentclass[twoside]{article}
  \usepackage[a5paper]{geometry}
  \usepackage{pgfmorepages}
  \pgfpagesuselayout{2 on 1}
  \usepackage[strict]{changepage}
\begin{document}

\checkoddpage
\ifoddpage
Odd Page
\else
Even Page
\fi

\newpage

\checkoddpage
\ifoddpage
Odd Page
\else
Even Page
\fi

\end{document}
```
2. Compile with `xelatex test.tex`
3. Examine output.

![CleanShot 2023-12-21 at 17 12 53@2x](https://github.com/loopspace/pgfmorepages/assets/39023/a8d63f16-db4a-4d11-8d2a-aa320d0ee4f6)

# Expected Results

That the left page says odd, and the right page says even.

**Comment by loopspace** [comment]
This is a known issue inherited from `pgfpages`.  The PGF manual explains and gives the solution (current version of the manual has this on p1014):

> Another word of caution: _using `pgfpages` will produce wrong page numbers in the `.aux` file_. The reason is that TeX instantiates the page numbers when writing an `.aux` file only when the physical page is shipped out. Fortunately, this problem is easy to fix: First, typeset our file normally without using the `\pgfpagesuselayout` command (just put the comment marker `%
before it) Then, rerun TeX with the `\pgfpagesuselayout` command included and add the command `\nofiles`. This command ensures that the `.aux` file is not modified, which is exactly what you want.
